### ISSUE TITLE
Deployment History

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#169]
It can be hard to debug what's going on in a service if you are unsure which version of the service is currently up and running.

It would be practical to have a deployment log which includes things like:

- when the build started
- when the build completed
- when the service first showed up as healthy (if at all)

Doing `defang ls` would provide that additional context... something like 

```
services:
    - service:
        name: ui
        deploymentTriggeredAt: 2024-03-06T20:50:40Z
        buildCompletedAt: 2024-03-06T20:54:40Z
        builtIn: 5m21s
        readyAt: 2024-03-06T20:59:40Z
```

That additional context can be helpful in getting a quick/rough understanding of how deployments are going, and what is currently live.
