### ISSUE TITLE
Need a better way to do local dev with secrets

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#203]
At the moment, something like this doesn't work:

```yaml
version: '3.9'
name: slack-invite-bot
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
        published: 8080
    secrets:
      - SLACK_TOKEN
      - SLACK_CHANNEL_ID
      - SLACK_WORKSPACE_ID
secrets:
  SLACK_TOKEN:
    external: true
  SLACK_CHANNEL_ID:
    external: true
  SLACK_WORKSPACE_ID:
    external: true
```

If I try to `docker-compose up` with that, I get:

```
unsupported external secret SLACK_TOKEN
```

Apparently the secrets config only works in swarm mode.

As I've been testing, I've just been deploying that sort of thing without running locally, but there are many cases where local dev is just much more practical, so I think we need to find a better way.

I've personally never used the `secrets` config in `compose.yaml` before. I've also never used compose in production, only in dev. My assumption has always been that in dev, we'll use a `.env` file or something, and then in production secrets will be managed by some other system which will just pass them as env vars to the container. 

My understanding is that this is a pretty common practice. So if we want Defang to be easy for many people to run who are familiar with compose, then we shouldn't use `secrets`, since many will expect to be able to do local dev first.
