### ISSUE TITLE
Published ports w/ ingress?

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#205]
To run this example locally, I had a port with `target` and `published` set:

```
version: '3.9'
name: slackbot
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
        published: 8080
    secrets:
      - SLACK_TOKEN
      - SLACK_CHANNEL_ID
      
secrets:
  SLACK_TOKEN:
    external: true
  SLACK_CHANNEL_ID:
    external: true
```

This is useful for local dev (though note that I had to remove secrets, use env vars, and then switch back to deploy). 

But when I try to deploy with the target and published set, I get the following error:

```
WARNING Published ports are not supported in ingress mode; assuming 'host' (add 'mode' to silence)  target=8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x103370248]

goroutine 1 [running]:
github.com/defang-io/defang/src/pkg/cli.validateProject(0x1400013b360)
        /Users/runner/work/defang/defang/src/pkg/cli/composeStart.go:264 +0xef8
github.com/defang-io/defang/src/pkg/cli.ComposeStart({0x103f95778, 0x1400036c820}, {0x103fa1d10?, 0x140000ec1e0?}, 0x1400013b360, 0x0?)
        /Users/runner/work/defang/defang/src/pkg/cli/composeStart.go:276 +0x48
main.glob..func11(0x104a02d00, {0x104a44970?, 0x0?, 0x0?})
        /Users/runner/work/defang/defang/src/cmd/cli/main.go:441 +0xa8
github.com/spf13/cobra.(*Command).execute(0x104a02d00, {0x104a44970, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x7e4
github.com/spf13/cobra.(*Command).ExecuteC(0x104a004c0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x380
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
main.main()
        /Users/runner/work/defang/defang/src/cmd/cli/main.go:886 +0x1410
```
