### ISSUE TITLE
Secrets are actually environment variables

### ISSUE THREAD

**Issue by lionello** [defang-io/defang#217]
Relates to #203 

From https://github.com/compose-spec/compose-spec/blob/master/05-services.md#environment
> Environment variables can be declared by a single key (no value to equals sign). In this case Compose relies on you to resolve the value. If the value is not resolved, the variable is unset and is removed from the service container environment.

Current compose files like:
```
services:
  a:
    secrets:
      - BLAH
secrets:
  BLAH:
    external: true
```
should actual be written like:
```
services:
  a:
    environment:
      - BLAH
```
and generate the same internal protobuf definition (still with "service.secrets" for now)
