### ISSUE TITLE
Incorrect Route 53 records in BYOC

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#353]
For this service:

```
version: '3.7'
name: hasura-rds
services:
  hasura:
    networks:
      - public
    image: hasura/graphql-engine:v2.39.0.cli-migrations-v3.ubuntu
    ports:
      - target: 8080
        published: 8080
        mode: ingress
    environment:
      - HASURA_GRAPHQL_DATABASE_URL
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
```

I would expect the following host:
```
hasura.hasura-rds.raphaeltm.defang.app
```

And indeed, that is what shows up in the load balancer listener rules:

![CleanShot 2024-05-09 at 13 01 53@2x](https://github.com/defang-io/defang/assets/910895/070db4fe-d2ee-47ab-bad9-9485c353a8fe)

But the A record in Route 53 is the following:
```
hasura-rds.hasura-rds.raphaeltm.defang.app
```

![CleanShot 2024-05-09 at 13 04 22@2x](https://github.com/defang-io/defang/assets/910895/af227956-0778-4532-9046-7e54826dc253)
