### ISSUE TITLE
Specify Healthcheck Details

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#46]
Being able to specify the following would be really helpful:

```
healthcheck: 
    test: ["CMD", "curl", "-f", "http://localhost:3000/"]
    interval: 1m30s
    timeout: 30s
    retries: 20
```
